name: Get logged time
on:
  workflow_call:
    inputs:
      github-token:
        required: true
        type: string
      base-branch:
        required: true
        type: string

jobs:
  should_run:
    runs-on: ubuntu-latest
    outputs:
      should_run: ${{ steps.check_changes.outputs.should_run }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2

    - name: Get changed files
      id: check_changes
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD~1..HEAD)
        echo "Changed files: $CHANGED_FILES"
        RUN_JOB='false'
        for FILE in $CHANGED_FILES
        do
          if [[ "$FILE" == ".ptyme_track/"* ]]; then
            RUN_JOB='true'
            break
          fi
        done
        echo "should_run=$RUN_JOB" >> $GITHUB_OUTPUT
  log_time:
    needs: should_run
    permissions:
      pull-requests: write
    runs-on: ubuntu-latest
    if: ${{ needs.should_run.outputs.should_run == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python 3.11
        uses: actions/setup-python@v3
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install --no-interaction
      - name: Do poetry install
        run: poetry install
      - name: Fetch from git
        run: git fetch --depth=1 origin
      - name: Run command and save output
        id: run-command
        uses: mathiasvr/command-output@v2.0.0
        env:
          PTYME_TRACK_BASE_BRANCH: ${{ inputs.base-branch }}
        with:
          run: poetry run ptyme-track --git-ci-times
      - name: Comment on time spent
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ inputs.github-token }}
        with:
          script: |
            const output = `${{ steps.run-command.outputs.stdout }}`;
            const comment = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: output
            });
            console.log(`Comment created: ${comment.data.html_url}`);
