on:
  pull_request:
    types: [opened, synchronized]
    # paths:
    #   - '.ptyme_track/*'

jobs:
  log_time:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install --no-interaction
      - name: Do poetry install
        run: poetry install
      - name: Run command and save output
        id: run-command
        env:
          PTYME_TRACK_BASE_BRANCH: ${{ github.event.pull_request.base.ref }}
        run: |
          echo "<< $PTYME_TRACK_BASE_BRANCH >>"
          poetry run ptyme-track --git-ci-times
      - name: Comment on time spent
        uses: actions/github-script@v4
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const output = '${{ steps.run-command.outputs.stdout }}';
            const context = github.context;
            const comment = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: ${output}
            });
            console.log(`Comment created: ${comment.data.html_url}`);
