name: Get logged time
on:
  pull_request:
    paths:
      - '.ptyme_track/*'

jobs:
  should_run:
    runs-on: ubuntu-latest
    outputs:
      run_job: ${{ steps.check_changes.outputs.run_job }}

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Get changed files
      id: check_changes
      run: |
        CHANGED_FILES=$(git diff --name-only HEAD~1..HEAD)
        echo "Changed files: $CHANGED_FILES"
        RUN_JOB='false'
        for FILE in $CHANGED_FILES
        do
          if [[ "$FILE" == ".ptyme_track/"* ]]; then
            RUN_JOB='true'
            break
          fi
        done
        echo "::set-output name=should_run::$RUN_JOB"
  log_time:
    permissions:
      issues: write
    runs-on: ubuntu-latest
    if: ${{ needs.check_changes.outputs.should_run == 'true' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          python -m pip install --upgrade poetry
          poetry install --no-interaction
      - name: Do poetry install
        run: poetry install
      - name: Fetch from git
        run: git fetch --depth=1 origin
      - name: Run command and save output
        id: run-command
        uses: mathiasvr/command-output@v2.0.0
        env:
          PTYME_TRACK_BASE_BRANCH: origin/${{ github.event.pull_request.base.ref }}
        with:
          run: poetry run ptyme-track --git-ci-times
      - name: Comment on time spent
        uses: actions/github-script@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          script: |
            const output = `${{ steps.run-command.outputs.stdout }}`;
            const comment = await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body: output
            });
            console.log(`Comment created: ${comment.data.html_url}`);
