name: Get logged time
on:
  pull_request:
    # paths:
    #   - '.ptyme_track/*'

jobs:
  track-time:
    uses: ./.github/workflows/time_tracking.yaml
    with:
      base-branch: origin/${{ github.event.pull_request.base.ref }}
