name: Get logged time
on:
  pull_request:
    paths:
      - '.ptyme_track/*'

jobs:
  track-time:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/workflows/time_tracking.yaml
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-branch: origin/${{ github.event.pull_request.base.ref }}
